name: 'Main'

on:
  push:
    paths:
      - 'typescript/**'
      - 'dart/**'
      - 'kotlin/**'
    branches:
      - 'main'
  pull_request:
    paths:
      - 'typescript/**'
      - 'dart/**'
      - 'kotlin/**'
    branches:
      - 'main'

env:
  KEYSTORE_HOST: '${{ secrets.KEYSTORE_HOST }}'
  KEYSTORE_ACCESS_TOKEN: '${{ secrets.KEYSTORE_ACCESS_TOKEN }}'

jobs:
  Check:
    name: 'Check git changes'
    runs-on: 'ubuntu-latest'

    outputs:
      typescript: '${{ steps.check-dirs.outputs.typescript }}'
      dart: '${{ steps.check-dirs.outputs.dart }}'
      kotlin: '${{ steps.check-dirs.outputs.kotlin }}'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Check changed directories'
        id: 'check-dirs'
        run: 'chmod +x scripts/github/check_changed_dirs.sh && scripts/github/check_changed_dirs.sh'

  Typescript:
    runs-on: 'ubuntu-latest'
    needs:
      - 'check'

    if: ${{ needs.check.outputs.typescript == 'true' }}

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Setup Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@evgenii-shcherbakov'
          always-auth: 'true'
      - name: 'Build libraries with changes'
        if: ${{ github.event_name == 'pull_request' }}
        run: 'chmod +x scripts/main.sh && scripts/main.sh typescript build'
      - name: 'Build & publish libraries with changes'
        if: ${{ github.event_name == 'push' }}
        run: 'chmod +x scripts/main.sh && scripts/main.sh typescript publish'

  Dart:
    runs-on: 'ubuntu-latest'
    needs:
      - 'check'

    if: ${{ needs.check.outputs.dart == 'true' }}

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Setup Dart'
        uses: 'dart-lang/setup-dart@v1'
      - name: 'Build libraries with changes'
        if: ${{ github.event_name == 'pull_request' }}
        run: 'chmod +x scripts/main.sh && scripts/main.sh dart build'
      - name: 'Build & publish libraries with changes'
        if: ${{ github.event_name == 'push' }}
        run: 'chmod +x scripts/main.sh && scripts/main.sh dart publish'

  Kotlin:
    runs-on: 'ubuntu-latest'
    needs:
      - 'check'

    if: ${{ needs.check.outputs.kotlin == 'true' }}

    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
      - name: 'Load code'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 2
      - name: 'Setup Java'
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: 19
      - name: 'Build libraries with changes'
        if: ${{ github.event_name == 'pull_request' }}
        run: 'chmod +x scripts/main.sh && scripts/main.sh kotlin build'
      - name: 'Build & publish libraries with changes'
        if: ${{ github.event_name == 'push' }}
        run: 'chmod +x scripts/main.sh && scripts/main.sh kotlin publish'
